swagger: '2.0'
info:
  title: Hello World
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Say hello to the world
      operationId: greet
      responses:
        200:
          description: Sweet success
          schema:
            $ref: get-response.json
