swagger: '2.0'
info:
  title: Hello World
  version: 1.0.0
paths:
  /hello:
    get:
      operationId: greet
      responses:
        200:
          description: Sweet success
          schema:
            $ref: get-hello-response.json
  /hai:
    get:
      operationId: hai
      responses:
        200:
          description: Sweet success
          schema:
            type: string
