swagger: '2.0'
info:
  title: Stranger Things
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
paths:
  /characters:
    get:
      operationId: getCharacters
      responses:
        200:
          description: List of characters
    post:
      operationId: postCharacter
      parameters:
        - name: name
          in: body
          required: true
          schema:
            type: string
      responses:
        201:
          description: Successfully added character

  /characters/{characterId}:
    get:
      operationId: getCharacter
      responses:
        200:
          description: Character

  /search:
    get:
      operationId: searchCharacters
      parameters:
        - name: q
          in: query
          type: string
          required: true
      responses:
        200:
          description: Character search results
