swagger: '2.0'
info:
  title: Stranger Things
  version: 1.0.0
produces:
  - application/json
paths:
  /characters:
    get:
      operationId: getCharacters
      responses:
        "200":
          description: list the characters
    post:
      operationId: postCharacter
      parameters:
      - name: name
        in: body
        required: true
        schema:
          type: string
      responses:
        "201":
          description: Successfully added character
  /search:
    get:
      operationId: searchCharacters
      responses:
        "200":
          description: character search results
