swagger: '2.0'
info:
  title: Stranger Things
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
paths:
  /characters:
    get:
      operationId: getCharacters
      responses:
        200:
          description: List of characters
    post:
      operationId: postCharacter
      parameters:
        $ref: post-character.yml#/parameters
      responses:
        201:
          description: Successfully added character
