swagger: '2.0'
info:
  title: Stranger Things
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
paths:
  /characters:
    get:
      $ref: get-characters.json
    post:
      $ref: post-character.yml
